/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the models the gateway offers right now (read live on every call), and the tiers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Models"];
                    };
                };
                /** @description gateway_unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description this API's OpenAPI 3.1 document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            openapi: string;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description every project, newest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": (components["schemas"]["Project"] & {
                            partCount: number;
                            stuckCount: number;
                        })[];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description a new project */
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        organisationId?: string;
                        theme?: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description too_large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the live spec */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            links: components["schemas"]["Link"][];
                            parts: components["schemas"]["Part"][];
                            project: components["schemas"]["Project"];
                        };
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            /** @description the chat model and/or creativity (temperature 0–2); at least one */
            requestBody: {
                content: {
                    "application/json": {
                        creativity?: number;
                        /** @description "tier:small|medium|flagship" or "<provider>/<model>" from GET /v1/models */
                        model?: string;
                    };
                };
            };
            responses: {
                /** @description the project as it is now */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description gateway_unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/projects/{projectId}/amendments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            /** @description a change request from a CAW worker — lands in the chat; the spec is not touched */
            requestBody: {
                content: {
                    "application/json": {
                        about?: string[];
                        from: string;
                        request: string;
                    };
                };
            };
            responses: {
                /** @description the `caw` chat message */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/change-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            /** @description changes applied all or nothing */
            requestBody: {
                content: {
                    "application/json": {
                        cause: components["schemas"]["Cause"];
                        changes: components["schemas"]["Change"][];
                    };
                };
            };
            responses: {
                /** @description applied; temp refs → new keys */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            changeSetId: string;
                            keys: {
                                [key: string]: string;
                            };
                        };
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description too_large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/change-sets/{changeSetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    changeSetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description one change set: counts from its changes, and whether undo would be accepted now */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChangeSetRead"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/change-sets/{changeSetId}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    changeSetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the undo, as a new change set */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            changeSetId: string;
                        };
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description undo_conflict · confirm_blocked · nothing_to_confirm · already_confirmed · already_added · quiz_missing · quiz_not_100 · quiz_stale · quiz_closed · quiz_full · already_marked · not_markable · nothing_to_retry */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/diagrams/{kind}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    kind: "sequence" | "swimlane" | "flowchart";
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description drawing data, projected from parts and links on this read */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SequenceDiagram"] | components["schemas"]["SwimlaneDiagram"] | components["schemas"]["FlowchartDiagram"];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            /** @description a change request in words */
            requestBody: {
                content: {
                    "application/json": {
                        request: string;
                    };
                };
            };
            responses: {
                /** @description the parts of the latest confirmed version the request touches, best first — or notInSpec */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Located"];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description no_confirmed_version */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the newest `limit` messages, oldest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"][];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/parts/{key}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description every change to the part and to links touching it, oldest first */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoryEntry"][];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description a new quiz — it becomes the latest */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Quiz"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/quizzes/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the latest quiz, with its score and whether it is stale */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Quiz"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/quizzes/{quizId}/items/{itemId}/mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    quizId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            /** @description right or wrong (final); a wrong answer becomes an open question in the spec */
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        mark: "right" | "wrong";
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description the marked item */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuizItem"];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description undo_conflict · confirm_blocked · nothing_to_confirm · already_confirmed · already_added · quiz_missing · quiz_not_100 · quiz_stale · quiz_closed · quiz_full · already_marked · not_markable · nothing_to_retry */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/quizzes/{quizId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    quizId: string;
                };
                cookie?: never;
            };
            /** @description one question, answered from the spec only */
            requestBody: {
                content: {
                    "application/json": {
                        question: string;
                    };
                };
            };
            responses: {
                /** @description the item — `answered`, or `failed` when the bot could not answer (both 200) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuizItem"];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description undo_conflict · confirm_blocked · nothing_to_confirm · already_confirmed · already_added · quiz_missing · quiz_not_100 · quiz_stale · quiz_closed · quiz_full · already_marked · not_markable · nothing_to_retry */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            /** @description one chat turn: a message, accepted question keys, answers in the user's own words, questions to park — any mix; or `retry: true` alone to ask the bot again for the newest turn that failed */
            requestBody: {
                content: {
                    "application/json": {
                        accept?: string[];
                        answers?: {
                            key: string;
                            text: string;
                        }[];
                        message?: string;
                        park?: {
                            key: string;
                            reason?: string;
                        }[];
                        /** @enum {boolean} */
                        retry?: true;
                    };
                };
            };
            responses: {
                /** @description the round — every outcome is 200, including a bot that could not answer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Round"];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description undo_conflict · confirm_blocked · nothing_to_confirm · already_confirmed · already_added · quiz_missing · quiz_not_100 · quiz_stale · quiz_closed · quiz_full · already_marked · not_markable · nothing_to_retry */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description every source, oldest first, without text */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            createdAt: string;
                            id: string;
                            /** @enum {string} */
                            kind: "file" | "link";
                            mime: string | null;
                            name: string;
                            note?: string;
                            origin: {
                                channel?: string;
                                date: string;
                                note?: string;
                                /** Format: uuid */
                                sourceId?: string;
                                /** @enum {string} */
                                stamp: "operator" | "operator-delegated" | "team-proposed" | "customer-asked" | "customer-validated";
                            };
                            reason?: string;
                            sha256: string;
                            size: number;
                            /** @enum {string} */
                            status: "read" | "failed";
                        }[];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            /** @description a file (multipart: `file` + `origin` as a JSON string) or a link (JSON) */
            requestBody?: {
                content: {
                    "application/json": {
                        link: string;
                        origin: {
                            channel?: string;
                            date: string;
                            note?: string;
                            /** Format: uuid */
                            sourceId?: string;
                            /** @enum {string} */
                            stamp: "operator" | "operator-delegated" | "team-proposed" | "customer-asked" | "customer-validated";
                        };
                    };
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                        /** @description an Origin as a JSON string */
                        origin: string;
                    };
                };
            };
            responses: {
                /** @description added — `status` says whether its text could be read */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Source"];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description undo_conflict · confirm_blocked · nothing_to_confirm · already_confirmed · already_added · quiz_missing · quiz_not_100 · quiz_stale · quiz_closed · quiz_full · already_marked · not_markable · nothing_to_retry */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description too_large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description unsupported_file */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    sourceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description one source with its text */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Source"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/stuck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description what is stuck, computed on this read */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["StuckItem"][];
                        };
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    after?: number | null;
                };
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description confirmed versions after `after`, ascending, each with the keys added, changed and removed since the one before */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionFeed"];
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                };
                cookie?: never;
            };
            /** @description who confirms */
            requestBody: {
                content: {
                    "application/json": {
                        confirmedBy: string;
                    };
                };
            };
            responses: {
                /** @description confirmed and frozen */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version: number;
                        };
                    };
                };
                /** @description validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description undo_conflict · confirm_blocked · nothing_to_confirm · already_confirmed · already_added · quiz_missing · quiz_not_100 · quiz_stale · quiz_closed · quiz_full · already_marked · not_markable · nothing_to_retry */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description too_large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    version: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description a confirmed version, read from its frozen row */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Version"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/versions/{version}/parts/{key}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectId: string;
                    version: number;
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description a part as frozen in a confirmed version, with its neighbours, decisions, flows and open questions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartContext"];
                    };
                };
                /** @description not_found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Cause: {
            /** @enum {string} */
            kind: "operator" | "message" | "source";
            ref?: string;
        };
        Change: {
            body: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            kind: "work" | "step" | "interaction" | "role" | "screen" | "api" | "system" | "data" | "decision" | "question" | "contradiction";
            /** @enum {string} */
            op: "part.add";
            origin: {
                channel?: string;
                date: string;
                note?: string;
                /** Format: uuid */
                sourceId?: string;
                /** @enum {string} */
                stamp: "operator" | "operator-delegated" | "team-proposed" | "customer-asked" | "customer-validated";
            };
            ref: string;
            title: string;
        } | {
            body?: {
                [key: string]: unknown;
            };
            key: string;
            /** @enum {string} */
            op: "part.update";
            origin?: {
                channel?: string;
                date: string;
                note?: string;
                /** Format: uuid */
                sourceId?: string;
                /** @enum {string} */
                stamp: "operator" | "operator-delegated" | "team-proposed" | "customer-asked" | "customer-validated";
            };
            title?: string;
        } | {
            key: string;
            /** @enum {string} */
            op: "part.remove";
        } | {
            from: string;
            /** @enum {string} */
            kind: "has_step" | "next" | "has_interaction" | "from" | "to" | "carries" | "reads" | "writes" | "shows" | "covers" | "about" | "conflicts";
            label?: string;
            /** @enum {string} */
            op: "link.add";
            origin: {
                channel?: string;
                date: string;
                note?: string;
                /** Format: uuid */
                sourceId?: string;
                /** @enum {string} */
                stamp: "operator" | "operator-delegated" | "team-proposed" | "customer-asked" | "customer-validated";
            };
            position?: number;
            to: string;
        } | {
            id: string;
            label?: string;
            /** @enum {string} */
            op: "link.update";
            position?: number;
        } | {
            id: string;
            /** @enum {string} */
            op: "link.remove";
        };
        ChangeSetRead: {
            at: string;
            cause: {
                kind: string;
                ref: string | null;
            };
            counts: {
                added: number;
                removed: number;
                updated: number;
            };
            entities: string[];
            id: string;
            undoable: boolean;
        };
        Error: {
            error: {
                code: string;
                details?: {
                    [key: string]: unknown;
                };
                message: string;
            };
        };
        FlowchartDiagram: {
            arrows: {
                from: string;
                label: string | null;
                to: string;
            }[];
            nodes: {
                ends: boolean;
                isBranch: boolean;
                key: string;
                position: number | null;
                title: string;
            }[];
        };
        FrozenQuiz: {
            createdAt: string;
            id: string;
            items: {
                answer: string | null;
                /** @enum {string|null} */
                mark: "right" | "wrong" | null;
                notInSpec: boolean;
                note: string | null;
                parts: string[];
                position: number;
                question: string;
                /** @enum {string} */
                status: "answered" | "failed";
            }[];
            marked: number;
            right: number;
            score: number | null;
        } | null;
        HistoryEntry: {
            after?: unknown;
            at: string;
            before?: unknown;
            cause: {
                /** @enum {string} */
                kind: "operator" | "message" | "source" | "undo";
                ref?: string;
            };
            changeSetId: string;
            entity: string;
            /** @enum {string} */
            op: "add" | "update" | "remove" | "restore" | "link_add" | "link_update" | "link_remove";
        };
        Link: {
            fromKey: string;
            id: string;
            /** @enum {string} */
            kind: "has_step" | "next" | "has_interaction" | "from" | "to" | "carries" | "reads" | "writes" | "shows" | "covers" | "about" | "conflicts";
            label: string | null;
            origin: {
                channel?: string;
                date: string;
                note?: string;
                /** Format: uuid */
                sourceId?: string;
                /** @enum {string} */
                stamp: "operator" | "operator-delegated" | "team-proposed" | "customer-asked" | "customer-validated";
            };
            position: number | null;
            toKey: string;
        };
        Located: {
            candidates: {
                key: string;
                kind: string;
                matched: string[];
                score: number;
                title: string;
                where: ("title" | "body" | "link label")[];
            }[];
            notInSpec: boolean;
            version: number;
        };
        Message: {
            changeSetId: string | null;
            content: string;
            createdAt: string;
            creativity: number;
            id: string;
            model: string;
            /** @enum {string} */
            role: "user" | "bot" | "caw";
            roundStatus: string | null;
        };
        Models: {
            models: {
                [key: string]: string[];
            };
            tiers: ("small" | "medium" | "flagship")[];
        };
        Part: {
            body: {
                [key: string]: unknown;
            };
            createdIn: string;
            key: string;
            /** @enum {string} */
            kind: "work" | "step" | "interaction" | "role" | "screen" | "api" | "system" | "data" | "decision" | "question" | "contradiction";
            origin: {
                channel?: string;
                date: string;
                note?: string;
                /** Format: uuid */
                sourceId?: string;
                /** @enum {string} */
                stamp: "operator" | "operator-delegated" | "team-proposed" | "customer-asked" | "customer-validated";
            };
            title: string;
        };
        PartContext: {
            confirmedAt: string;
            decisions: components["schemas"]["Part"][];
            flows: {
                at: string[];
                steps: {
                    key: string;
                    position: number | null;
                    title: string;
                }[];
                work: {
                    key: string;
                    title: string;
                };
            }[];
            neighbours: {
                /** @enum {string} */
                direction: "out" | "in";
                label: string | null;
                /** @enum {string} */
                linkKind: "has_step" | "next" | "has_interaction" | "from" | "to" | "carries" | "reads" | "writes" | "shows" | "covers" | "about" | "conflicts";
                part: {
                    key: string;
                    kind: string;
                    title: string;
                };
                position: number | null;
            }[];
            part: components["schemas"]["Part"];
            projectId: string;
            questions: components["schemas"]["Part"][];
            version: number;
        };
        Project: {
            createdAt: string;
            creativity: number;
            id: string;
            model: string;
            name: string;
            organisationId: string;
            theme: string;
        };
        Quiz: {
            createdAt: string;
            id: string;
            items: components["schemas"]["QuizItem"][];
            marked: number;
            right: number;
            score: number | null;
            stale: boolean;
        };
        QuizItem: {
            answer: string | null;
            createdAt: string;
            id: string;
            /** @enum {string|null} */
            mark: "right" | "wrong" | null;
            notInSpec: boolean;
            note: string | null;
            parts: string[];
            position: number;
            question: string;
            questionKey: string | null;
            /** @enum {string} */
            status: "answered" | "failed";
        };
        Round: {
            changeSetId: string | null;
            contradictions: string[];
            failedSources: string[];
            messageIds: string[];
            questions: string[];
            reply: string | null;
            /** @enum {string} */
            status: "applied" | "no_changes" | "changes_rejected" | "bot_could_not_answer";
        };
        SequenceDiagram: {
            messages: {
                from: string | null;
                key: string;
                reply: string | null;
                text: string;
                to: string | null;
            }[];
            participants: {
                key: string;
                /** @enum {string} */
                kind: "work" | "step" | "interaction" | "role" | "screen" | "api" | "system" | "data" | "decision" | "question" | "contradiction";
                title: string;
            }[];
        };
        Source: {
            createdAt: string;
            id: string;
            /** @enum {string} */
            kind: "file" | "link";
            mime: string | null;
            name: string;
            note?: string;
            origin: {
                channel?: string;
                date: string;
                note?: string;
                /** Format: uuid */
                sourceId?: string;
                /** @enum {string} */
                stamp: "operator" | "operator-delegated" | "team-proposed" | "customer-asked" | "customer-validated";
            };
            reason?: string;
            sha256: string;
            size: number;
            /** @enum {string} */
            status: "read" | "failed";
            text?: string;
        };
        StuckItem: {
            between?: string[];
            key: string;
            /** @enum {string} */
            kind: "open_question" | "unlinked_part" | "flow_break" | "unconfirmed_guess" | "screen_without_api" | "contradiction";
            linkId?: string;
            /** @enum {string} */
            reason?: "unreachable" | "dead_end" | "unlabelled_branch" | "no_interactions" | "incomplete_interaction";
            title: string;
        };
        SwimlaneDiagram: {
            lanes: {
                key: string;
                /** @enum {string} */
                kind: "work" | "step" | "interaction" | "role" | "screen" | "api" | "system" | "data" | "decision" | "question" | "contradiction";
                title: string;
            }[];
            rows: {
                lanes: string[];
                step: {
                    key: string;
                    position: number | null;
                    title: string;
                };
            }[];
        };
        Version: {
            confirmedAt: string;
            confirmedBy: string;
            links: components["schemas"]["Link"][];
            parts: components["schemas"]["Part"][];
            quiz: components["schemas"]["FrozenQuiz"];
            summary: {
                links: number;
                parts: number;
                partsByKind: {
                    [key: string]: number;
                };
            };
            version: number;
        };
        VersionFeed: {
            changedSinceLatest: boolean;
            latest: {
                confirmedAt: string;
                version: number;
            } | null;
            versions: {
                changes: {
                    added: string[];
                    changed: string[];
                    removed: string[];
                };
                confirmedAt: string;
                confirmedBy: string;
                summary: {
                    links: number;
                    parts: number;
                    partsByKind: {
                        [key: string]: number;
                    };
                };
                version: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
